window.subtitleCatalog = {
  version: 1,
  importRoot: "subtitles",
  imported: {
    "7oOaPVq07g8": {
      status: "timed",
      source: "Manual bilingual action captions based on local scene timing and checked lyric references",
      file: "subtitles/7oOaPVq07g8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "WQtbFDPOdT8": {
      status: "timed",
      source: "Timed bilingual descriptive captions for no-lyrics lofi lullaby medley",
      file: "subtitles/WQtbFDPOdT8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "XqZsoesa55w": {
      status: "timed",
      source: "Manual bilingual lyric cues based on checked local video timing and common Pinkfong Baby Shark structure",
      file: "subtitles/XqZsoesa55w.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "TbKI-jjpPx8": {
      status: "timed",
      source: "Trimmed local Itsy Bitsy Spider segment with checked YouTube auto English captions and local Chinese translation",
      file: "subtitles/TbKI-jjpPx8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "ffeZXPtTGC4": {
      status: "timed",
      source: "Manual segmented bilingual phonics cues based on checked local video timing",
      file: "subtitles/ffeZXPtTGC4.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "75p-N9YKqNo": {
      status: "timed",
      source: "Manual segmented bilingual ABC cues based on checked local video timing",
      file: "subtitles/75p-N9YKqNo.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "WP1blVh1ZQM": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/WP1blVh1ZQM.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "wCio_xVlgQ0": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/wCio_xVlgQ0.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "SFE0mMWbA-Y": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/SFE0mMWbA-Y.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "ohHYABXMqUQ": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/ohHYABXMqUQ.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "frN3nvhIHUk": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/frN3nvhIHUk.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "ANChOA4SyL0": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/ANChOA4SyL0.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "Yq6qYbwqAk8": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/Yq6qYbwqAk8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "jYAWf8Y91hA": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/jYAWf8Y91hA.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "JXIILWwaHQc": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/JXIILWwaHQc.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "ij_eHTvhIlE": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/ij_eHTvhIlE.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "chxQb4YRC2U": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/chxQb4YRC2U.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "5_ShP3fiEhU": {
      status: "timed",
      source: "YouTube English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/5_ShP3fiEhU.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "zXEq-QO3xTg": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/zXEq-QO3xTg.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "YVgv1EFJZHc": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/YVgv1EFJZHc.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "wqvQAcloTRQ": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/wqvQAcloTRQ.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "ug1pI-Ephns": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/ug1pI-Ephns.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "OKbpLQp509Y": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/OKbpLQp509Y.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "lVFj91Z1AfM": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/lVFj91Z1AfM.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "lMQcwNZVUO8": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/lMQcwNZVUO8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "EqVHR2vIwIE": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/EqVHR2vIwIE.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "BdrZWu2dZ4c": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/BdrZWu2dZ4c.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "aUgy3u5Mvzk": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/aUgy3u5Mvzk.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "666UZRBO5q8": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/666UZRBO5q8.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "4XLQpRI_wOQ": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/4XLQpRI_wOQ.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "1jX8XyYvtWs": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/1jX8XyYvtWs.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "1Ziku4FLka4": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/1Ziku4FLka4.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "JV-D_K4drsA": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/JV-D_K4drsA.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "TJhfl5vdxp4": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/TJhfl5vdxp4.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "TdDypyS_5zE": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/TdDypyS_5zE.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "P-uznC3AmaE": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/P-uznC3AmaE.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "JRMAptlBgTk": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/JRMAptlBgTk.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "GoSq-yZcJ-4": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/GoSq-yZcJ-4.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "fXFg5QsTcLQ": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/fXFg5QsTcLQ.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "9UasekNr8KI": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/9UasekNr8KI.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "TCoQ_2WWwxQ": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/TCoQ_2WWwxQ.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "rfLLlxgE8nk": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/rfLLlxgE8nk.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "pZw9veQ76fo": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/pZw9veQ76fo.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "f_raDpgx_3M": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/f_raDpgx_3M.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "5oYKonYBujg": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/5oYKonYBujg.json",
      note: "Imported with scripts/import-subtitle.js",
    },
    "1GDFa-nEzlg": {
      status: "timed",
      source: "legacy",
      note: "Loaded from subtitles_data.js",
    },
    "7otAJa3jui8": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/7otAJa3jui8.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "2HOrFuhIcHA": {
      status: "timed",
      source: "legacy",
      note: "Loaded from subtitles_data.js",
    },
    "CRHvTTOR8Ns": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/CRHvTTOR8Ns.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "HGgsklW-mtg": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/HGgsklW-mtg.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "nrv495corBc": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/nrv495corBc.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "jdg50KzCR9w": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/jdg50KzCR9w.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "LFrKYjrIDs8": {
      status: "timed",
      source: "YouTube official English captions checked locally; Chinese translation added for HelloLILI",
      file: "subtitles/LFrKYjrIDs8.json",
      note: "Imported as standalone timed bilingual cues",
    },
    "yCjJyiqpAuU": {
      status: "timed",
      source: "legacy",
      note: "Loaded from subtitles_data.js",
    },
  },
  pendingPolicy: {
    status: "pending",
    fallback: "learning",
    label: "待导入逐句字幕",
  },
};
