window.subtitleSources = {
  version: 1,
  defaults: {
    officialVideoUrlTemplate: "https://www.youtube.com/watch?v={youtubeId}",
    status: "needs-source-review",
    rights: "unknown-or-platform-controlled",
    nextAction: "Find a verified subtitle file, user transcript, or manual family transcript before importing timed cues.",
  },
  statusLabels: {
    complete: "Timed bilingual subtitles imported",
    candidate: "Priority candidate for timed subtitle work",
    "needs-source-review": "Needs source review",
    "needs-rights-review": "Needs rights/source review",
  },
  priorityQueue: [],
  songs: {
    "1jX8XyYvtWs": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=1jX8XyYvtWs",
      nextAction: "No action needed unless the local video changes.",
    },
    "1GDFa-nEzlg": {
      status: "complete",
      rights: "legacy-local-cues",
      sourceUrl: "subtitles_data.js",
      nextAction: "No action needed unless replacing the legacy inline cues with a standalone subtitle file.",
    },
    "2HOrFuhIcHA": {
      status: "complete",
      rights: "legacy-local-cues",
      sourceUrl: "subtitles_data.js",
      nextAction: "No action needed unless replacing the legacy inline cues with a standalone subtitle file.",
    },
    "yCjJyiqpAuU": {
      status: "complete",
      rights: "legacy-local-cues",
      sourceUrl: "subtitles_data.js",
      nextAction: "No action needed unless replacing the legacy inline cues with a standalone subtitle file.",
    },
    "7otAJa3jui8": {
      status: "complete",
      rights: "traditional-public-domain-lyrics-with-local-translation",
      sourceUrl: "https://en.wikisource.org/wiki/Row%2C_Row%2C_Row_Your_Boat",
      nextAction: "No action needed unless the local video changes.",
    },
    "CRHvTTOR8Ns": {
      status: "complete",
      rights: "traditional-public-domain-lyrics-with-local-translation",
      sourceUrl: "https://en.wikisource.org/wiki/Baa_Baa_Black_Sheep",
      nextAction: "No action needed unless the local video changes.",
    },
    "HGgsklW-mtg": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikisource.org/wiki/Hickory_Dickory_Dock",
      nextAction: "No action needed unless the local video changes.",
    },
    "nrv495corBc": {
      status: "complete",
      rights: "traditional-public-domain-lyrics-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/Humpty_Dumpty",
      nextAction: "No action needed unless the local video changes.",
    },
    "jdg50KzCR9w": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikisource.org/wiki/Pat-a-cake",
      nextAction: "No action needed unless the local video changes.",
    },
    "LFrKYjrIDs8": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikisource.org/wiki/Rain%2C_Rain%2C_Go_Away",
      nextAction: "No action needed unless the local video changes.",
    },
    "75p-N9YKqNo": {
      status: "complete",
      rights: "manual-segmented-traditional-abc-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/The_ABC_Song",
      nextAction: "Optional: refine local timing if the video source changes.",
    },
    "5oYKonYBujg": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/Old_MacDonald_Had_a_Farm",
      nextAction: "No action needed unless the local video changes.",
    },
    "TbKI-jjpPx8": {
      status: "complete",
      rights: "youtube-auto-caption-source-with-machine-translation",
      sourceUrl: "https://www.youtube.com/watch?v=TbKI-jjpPx8",
      nextAction: "Local media is trimmed to the first Itsy Bitsy Spider segment for GitHub/Netlify size safety; polish this shorter caption set if it becomes a core learning asset.",
    },
    "f_raDpgx_3M": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/Hush,_Little_Baby",
      nextAction: "No action needed unless the local video changes.",
    },
    "pZw9veQ76fo": {
      status: "complete",
      rights: "traditional-rhyme-variant-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/Five_Little_Ducks",
      nextAction: "No action needed unless the local video changes.",
    },
    "rfLLlxgE8nk": {
      status: "complete",
      rights: "traditional-action-rhyme-variant-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=rfLLlxgE8nk",
      nextAction: "No action needed unless the local video changes.",
    },
    "TCoQ_2WWwxQ": {
      status: "complete",
      rights: "traditional-fingerplay-rhyme-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=TCoQ_2WWwxQ",
      nextAction: "No action needed unless the local video changes.",
    },
    "9UasekNr8KI": {
      status: "complete",
      rights: "traditional-public-domain-lyrics-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/The_Wheels_on_the_Bus",
      nextAction: "No action needed unless the local video changes.",
    },
    "fXFg5QsTcLQ": {
      status: "complete",
      rights: "traditional-public-domain-variant-with-local-translation",
      sourceUrl: "https://en.wikipedia.org/wiki/The_Muffin_Man",
      nextAction: "No action needed unless the local video changes.",
    },
    "GoSq-yZcJ-4": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=GoSq-yZcJ-4",
      nextAction: "No action needed unless the local video changes.",
    },
    "JRMAptlBgTk": {
      status: "complete",
      rights: "traditional-action-song-variant-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=JRMAptlBgTk",
      nextAction: "No action needed unless the local video changes.",
    },
    "P-uznC3AmaE": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=P-uznC3AmaE",
      nextAction: "No action needed unless the local video changes.",
    },
    "TdDypyS_5zE": {
      status: "complete",
      rights: "traditional-counting-song-variant-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=TdDypyS_5zE",
      nextAction: "No action needed unless the local video changes.",
    },
    "TJhfl5vdxp4": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=TJhfl5vdxp4",
      nextAction: "No action needed unless the local video changes.",
    },
    "1Ziku4FLka4": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=1Ziku4FLka4",
      nextAction: "No action needed unless the local video changes.",
    },
    "4XLQpRI_wOQ": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=4XLQpRI_wOQ",
      nextAction: "No action needed unless the local video changes.",
    },
    "666UZRBO5q8": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=666UZRBO5q8",
      nextAction: "No action needed unless the local video changes.",
    },
    "aUgy3u5Mvzk": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=aUgy3u5Mvzk",
      nextAction: "No action needed unless the local video changes.",
    },
    "BdrZWu2dZ4c": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=BdrZWu2dZ4c",
      nextAction: "No action needed unless the local video changes.",
    },
    "EqVHR2vIwIE": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=EqVHR2vIwIE",
      nextAction: "No action needed unless the local video changes.",
    },
    "lMQcwNZVUO8": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=lMQcwNZVUO8",
      nextAction: "No action needed unless the local video changes.",
    },
    "lVFj91Z1AfM": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=lVFj91Z1AfM",
      nextAction: "No action needed unless the local video changes.",
    },
    "OKbpLQp509Y": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=OKbpLQp509Y",
      nextAction: "No action needed unless the local video changes.",
    },
    "ug1pI-Ephns": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=ug1pI-Ephns",
      nextAction: "No action needed unless the local video changes.",
    },
    "wqvQAcloTRQ": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=wqvQAcloTRQ",
      nextAction: "No action needed unless the local video changes.",
    },
    "YVgv1EFJZHc": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=YVgv1EFJZHc",
      nextAction: "No action needed unless the local video changes.",
    },
    "zXEq-QO3xTg": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=zXEq-QO3xTg",
      nextAction: "No action needed unless the local video changes.",
    },
    "5_ShP3fiEhU": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=5_ShP3fiEhU",
      nextAction: "No action needed unless the local video changes.",
    },
    "7oOaPVq07g8": {
      status: "complete",
      rights: "manual-action-caption-with-lyric-reference",
      sourceUrl: "https://www.youtube.com/watch?v=7oOaPVq07g8",
      nextAction: "Optional: replace the manual action captions if a cleaner official transcript becomes available.",
    },
    "chxQb4YRC2U": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=chxQb4YRC2U",
      nextAction: "No action needed unless the local video changes.",
    },
    "ij_eHTvhIlE": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=ij_eHTvhIlE",
      nextAction: "No action needed unless the local video changes.",
    },
    "JXIILWwaHQc": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=JXIILWwaHQc",
      nextAction: "No action needed unless the local video changes.",
    },
    "jYAWf8Y91hA": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=jYAWf8Y91hA",
      nextAction: "No action needed unless the local video changes.",
    },
    "WQtbFDPOdT8": {
      status: "complete",
      rights: "instrumental-no-lyrics-descriptive-captions",
      sourceUrl: "https://www.youtube.com/watch?v=WQtbFDPOdT8",
      nextAction: "Optional: replace this no-lyrics lofi video if a vocal lullaby is preferred.",
    },
    "XqZsoesa55w": {
      status: "complete",
      rights: "manual-lyric-cues-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=XqZsoesa55w",
      nextAction: "Optional: refine local timing if the video source changes.",
    },
    "Yq6qYbwqAk8": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=Yq6qYbwqAk8",
      nextAction: "No action needed unless the local video changes.",
    },
    "ANChOA4SyL0": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=ANChOA4SyL0",
      nextAction: "No action needed unless the local video changes.",
    },
    "ffeZXPtTGC4": {
      status: "complete",
      rights: "manual-segmented-phonics-caption-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=ffeZXPtTGC4",
      nextAction: "Optional: refine local timing if the video source changes.",
    },
    "frN3nvhIHUk": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=frN3nvhIHUk",
      nextAction: "No action needed unless the local video changes.",
    },
    "ohHYABXMqUQ": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=ohHYABXMqUQ",
      nextAction: "No action needed unless the local video changes.",
    },
    "SFE0mMWbA-Y": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=SFE0mMWbA-Y",
      nextAction: "No action needed unless the local video changes.",
    },
    "wCio_xVlgQ0": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=wCio_xVlgQ0",
      nextAction: "No action needed unless the local video changes.",
    },
    "WP1blVh1ZQM": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=WP1blVh1ZQM",
      nextAction: "No action needed unless the local video changes.",
    },
    "JV-D_K4drsA": {
      status: "complete",
      rights: "official-caption-source-with-local-translation",
      sourceUrl: "https://www.youtube.com/watch?v=JV-D_K4drsA",
      nextAction: "No action needed unless the local video changes.",
    },
  },
};
